[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "5de3d605e43644b149dfccbce9c18720ac48047d"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "bd0f3352420d14a8d8aebf732e54ae548f7000a36783be1f38fa7ed762d1f64e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "d9ad4449210e5155ced49ae01175f10cf5bb81ca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "07fe9f23219655376d7f7d82869f93862ef6ed19dd05f87152c963e0b538e859"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "a4895cef415c2bec5260ece2c92ddceda490b1a6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d5db5b9bacd29c39cb59d0e3e890f9591d9400c87f917919aa4c4bb9ac35fbfd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "cb31ed2bdf9ba04aceb410b93bacbf31bea60b42"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "60e75bbd1dc38bcab77c6073a34f039558f4a0aabff750369f3ae66a3ad593b6"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "04e32a995c081b0873601302d10b55ac44b3b137"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0719d4bf9693e72ed10cabbb608da5aa6edddebb4d5e06d3d4fb34a7c6be9012"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "76d308c02e9ae1b30d733be768467d93ca1ccff6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "bfbde6de0feb93b84637ac7b8acf722a45ab99251c03a27dfbf557af6e843710"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "bdee44da922d7411266571e67bfa37dbe58b9bb1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5f2a2ce223b3e434999dea0f7761d4e89e51e344c98694555c64fd1dd37dd2bd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22f3667ee11ad87266ff6a41df965a4102f1fac7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d01a1de334e1dc77d04b40e7a4535acdd2e25527441fd2ee741c6ab4948b1191"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "40bf2719414deb634a5c569a3a1911a893affbfa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "dffa25d77fac8a72a8a7d356ae2adc4cdd47b65cde23469cebb0a2fe98dbca7f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7e78cb96f78f2b122119faa4b29d176dc49fdc03"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "553fcb7d523c9df369d11f18e46de0621f980ea3516493fa60d2e13362b17dbe"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ec54b0c4379ee03faa833b34fe31fb68e9e38dd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "eac7256b6a57e82897ec363e5012dfa331af07b06c5321d25623a9960311bca1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d304612d300ad1e23362982a18fb36c4a561c495"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c2ae7814a007cf3e97d8933e964176f8359db8e0ad8f91843ebd3eb2fb48e6c8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fbe43074de8e0278a6557db8c240b83c406b9db4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5138679344a2abbc90f974b9e4138cca000ff76f9acc8f2fab340973005f6a4a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee92bd52ea056df74cc0591f54586cca5a9b2372"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "71d917eb269c054f90cd609073f2d5afcf4d2d7d28fdea0757c7e993a545237f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "74eda5dde74c539d8f677f1418eb91891a29287b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a4e51e3a5e295bd1a9b2fb529d6655b7dc2bb39f6dea6fe4cb43bf579b934538"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8a8e1d6afb77377dc472ea64b8f6cc316eaafc5c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "1b3e0a4f82a574584c5bfb9a01222a23d234870e8d8f4ecdca21c898a5c682aa"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef60915a0de322df7cd95cc3f200a4bb26cf9428"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "209d8f4d482c8c5d3d402bf9a8d784389cacc65dc8c8e0b22646b81d3c014d03"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "19fcc7eb4c2d858b252b024b20e370fdfd2a3e84"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f9ede87de54e2b4770fb5f6e1143d1b0144b81cbc48c55ab7abe3bc323811942"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "30dfd9f7e08186e5fc873bbca2c1627acf7169e4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "538e6c38c182f904c046a0eaba76a9457c94e456810a052cbfd9487693a784b1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "715eef641f5a12b0869b96973e9b73981dbe3c52"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ceeb970560ca837dae47fee2ec7450a4d04d9e54c98eecd27ba3f321b4fc0774"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "f33296cee357cd003b48b050233e6ac067a4b560"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "90b63a1c0502591a2de5f92801124ea916dedb7beea339cf91049a3e341ca131"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "082ea3dc9a973b6d9b267d429f000447b4371226"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "61374121bba4649656b95036d3ee901e006c1632d5a2aa407f80a343c109236f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "32e233993cdfd6e9bc1bcdbd6c902f5f6b280956"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3bd2baeabf3f837a7733a576031bcea61ebdde6c8b920e50b3e2453fc440795d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "d2c56bee6a8bba0c1de8f217a26467fe272343eb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7fb1924fc29e7f965721c43ab54db65adb6cf072823f68512fca250b3663ac7a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "41097908b97a3cd4d3488cc594b00d52b1acbf0a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c5570e44f5609d51db242f16f4f3a90cc29a4e238072c065f76df91cbeb6e3a5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c5fa4f49e1a9827e5838aa7c9788440a60ec5223"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "15a178e46cc8261a9901260c1478c2ad74464722f7ed6dfb22c56985fc117b62"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "d9714355f4558ce738e5a71d514a91f728ddfbc6"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "949838e3b8ed2e8a1effa0ccc24ffa1aee74eaa684e8417537ca5882a10ed71f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "409212a803e40f57db32d331c0b2512a52cf6a9b"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "e33a466a865ca37a3f221044513e6f13b5aadd97756d3837baeb2569260e5877"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "ad24fdd51221071e119f3296fa5bd9b65ccacd0e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "89ce567a9a00e72bc55fda0592c7e82750b093eaf7693dbb708b72068a0f38e0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "f2b28ea51947e098a23510baef67a0218fbfbdcd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4cb9056c08a259ff8609d07b755f788cef414aeb796119e636aabe8fa45d3317"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "e19a2fdd9f19daa12cb51b058b7d54c040d6b28f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "995d584bd4130f3ec4acdeec1a398a1bf2c0108f5c8d7c7825536fcf07d0e4cf"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "445beb99013d72db493188985d914f70dbd7d99e"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "436e4bfe4b5ccea82df11f9d7008daad9362cadc4831a2c108b7d5bdd2af489d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "8e8f2ac31cd0d90dfd573e46e131ace0e663c933"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "fe58ec86574b7c483894506acafffdc814650c323c070558189faadbc80abbfa"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ec366f1a173a6c9fdbbe1649a3652593e8110fd3"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "83196a583a778acbdc8a62c850d7c93960bf5b091af2fb5eeb65c69a5acd2e5c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "d7e206689fe1e0c9483f2215cc3baaf14c78e638"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "534b76521c792b8877b6943abcf01f0c6e3a70865a008b72a6c7023bfd06b2cc"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "db557dae16b5e00ae828c61384c437366a50aebe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "519eade1abe3f2dcbc08711f5106bbc0cc16d7135e9c1b8eca49452ac15183b4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "de611fad98f0257bea3161b82e8e9575e9b4f93b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a448826759d34faa3928a4c2bc64f49cfca82103b564ec4c7047673d20ab5712"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "2c1d4a183235e96863cfbbe986e6ec7cddabc69b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ef729ec1adca90a7bdcd4bc988fe92c038da93aabd16c000925b6a5f79d5d292"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f0f1221ebe08d40fc937c9cae149d19370e2a15f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4c91df0cf2850c5ee9db25a4b41d3b598a6f843acb9dde66029292443629abcb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "71ddbd99a9bbc5208dc85358a9d20f5b3db11f32"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c9dd34baee18bdb02bc4ad2dd92e54fe7dee7354b2ee3d258759ff9ff26c9a78"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "080e59070ad7db614f636a2f6e3c4363097df392"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "da4c2ec0d1da3d4aeacd010ed2508d0aa046d4ed75fb82e92440ef65de763818"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "073933502643fd048f7a95ae4b20e233d5813365"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "c194c946d20856fe1ec43d3a91852e33942d7de8ec8a80c8f1bfb0c2bdf70c83"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "4071046c42c0bbaafc593d21f80edca97fdba820"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "5337425b0af7f3796f4ede11c993d1c83e9b9b9f66df78fb95bdea2e1a903ec2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "1d91f76dcd384facf727bc7e4b26de042eb94663"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "fb409ef706fd0dd8805cd6bc4ab07575325c60ea6cb14c1d8223d0f52b005c8b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "faaba0d8ad226d73ecf674ee4930bc3d879be508"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "ee0a5069869c6eadeebc7fd613cb907cf634620fb727357b8c05354f723e5c2c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "e9b19bcb478ff589bac1f51ef318876d3e1b031f"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "057c99a7213ff9969810ed4855451084727ab226cc4ef1d6991f6fdef7aeaa72"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.9+0/Perple_X.v7.0.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
