[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "c531413f000dd8b0da11acb40d10515ab0c22617"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "ef68e594e9d645d8c14de332ee49178bad6ae3c48f49609261fe93e2ad85ac62"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "ad98098c2ca9dd61b01217a2d17aa6790c3e26b4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ec25ee895beccca1d76dc0a01920e6331c233e7f3c0a0abf8692a0b6051c49fb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "2d757fa910978164224ea77e5ef3a22119963aea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f1a535ba66182f4de4327182847a8e54aafc84ba6cd84649f0456936e7383c7c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "52bfd5edba979030dc1fd1cf49b2f10c348faa39"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "50d2a707fd33068d75ed1d654b5c1b7f3c00a97a87a20e98706fd49228bc0fec"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "4686f47bca3db3dc9c8c94f165cd5c8e6b9c5c13"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "eb9d96864eb8f153bb1ba1ba8ebd508f7306d86cb08a6660b3cc6a76f703ad4f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "a440ac555645bf758ed195f45bae22c4511605ff"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9fc1241939d41d13dafbfdb4494d522c2577f5a43563bd9334774963ae336661"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "989f8a83c706da0f4ba0d06cb7d285a64b1d8d40"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e0be199af5d7e418fdaa3f912f2f3f7b307abfaeda2314c42f12c48a0fe5e935"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eee492d937ac8e4a998e384aabbe636fbff69d64"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "1d552498fe6ac28c2bb3afa71810a14fed3599b28e6a5b37f0d9c425b805edc5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b8740f637f4758f810bbae03ad84e076b7b906ab"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9764bafd7a44a2a6a9fe957239581d0325b267c3fe88b5f4e07ae2aaacc21b9e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4befc37e3887a01e3cbbd4e218d8cab1ccbb51ff"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c3e918169c6ec02631d19068dd0f92d1d374c038988a8cd96ae098a92bdbc357"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "080e8076ca0a84cf5dcf9fb0ca616a8e0ad07743"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f2c2d8bbe98fd55f30bd76757df3f25bd92f207fd83efefa07193a7dac43bc9f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "210fdaf0ebc4e703df6f7a05dba9a1c99f13ac38"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8047f793aed668fc6c269f8133a5c6bdf4c998bf5798f263b437142ea36f4f6e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed6cb6e7a8ff5b9a0452ca233152fa41e3d7d13e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "bef39543130a448d6b9fd7f658955755c9908b53e8a27031d6935fb2e36ef60b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4c35f4dd6459ff1df6e08423be29cef81b39431e"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3bc5757e2b9db1b80145b7b8f3a5e77910c96c1b25c393487bb9a0d0c2987455"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8aa2494f17b72c4fc031ebdf693aaca8510b99fd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d4e2c51ef0cbfdbffd2e417db62d3517652ccce091a655b27e012e1a1d00d120"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d0a10078d6f53925d2798647b3a580ab5655b02"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0f9931d71f8e012c6b6d11123c06c6ab1c7b082efcdcabcca94b80b144cd8013"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0de2a53b607afa8719727ed05f319f270cfb4af3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "64be42505083b91a9cfc770352878d2bb1532c267d8d06cf05db189a5bc26845"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b91c315aa685fb0e9975d00f7df9968ba3e34a20"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f090ce9a898c665fe89a467f7c80ea82375ba36daba1fbe4b71d1a209dc7621c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dd4dbb9eeadd10433efc447669d938b1f87e2af4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "bf21a8cff6feff74f4c2fa7e0325d7cb9dd5381a2711b5488480feafa1aa2786"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "3f05f646bdf9cf11243a3355c2ccca79f4c669c6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "40e1cba97102d7e130eaa5ba5b894d44c5fd2efb3aaa75befd828ce20a657769"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "3fc1c79a7783b06a81f6e268981decb632a48257"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d733c948d6be05dedca0d3ba79313c86798f9b86ded1a438514a6c83264fc85f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "38ea63f81d0ecf60a7dfb74793aefc5a13409b9a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0df07e6cc05b789f3d0af046f356b23e475b85c9d0c5d64c14d6110fd6ae3e4b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c3b78fb21d208ff35d468f3462155cb1e41f14b1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5730c09b518d0cae3e1d92ccf71e7a3db2bdf949e06b8fe92f822a35df59e768"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "1d98b66e1daf2e166fae3bf6eed60f409436376c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "afd89c1bac0be66af7df89b046f29043f7fb26578a1515c1f0a557031db605cc"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "df9562f6ca1af6c9c41034e675f75f60b5df6149"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "43e3dec91862df6e7944e399d04a14ed2f7d285e7a6844a6c4034a06b870b6c1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "eb4d0d097ecbf4ec43cb473106fb0a35581e1b01"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "247850bab492320f97fdf79e2cf60673313ef7c7ab253489e1abb1ffac527c37"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "5de50d25cfc95a8e4d7c86bafcc1ffd5c9c6a22d"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "ffe4a29f9967b0603714a384c412a1b827b8fd21f78e9fa8bc06472a700802ce"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "41e8a155375d154c14b69aa812221ad46ec6edf0"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "d74eb2144b3f4e0ac0b69c6f9ec02cca064fedf58e3f9e486dc46495282aa9bd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "9cd485616be17f19460167359ceec2435b3eb82a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7fe9e6ff22721bbecc4e24296520b4e09766aefd9c3d1c15982c18b974191a72"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "816d06da04ff1b797e7e57a2c8720b700fd7a6bf"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f0907e2e09a9e586c1486048388b59e9de30ab9b8a2a2cfdd7850c703f65d278"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "c469c3daad0fe1750bb2a615e55d26dcd6df5925"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "58987923a3544f4e998f254024a9892618ec18b4e07bfb1406b66d5cf4a11f16"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "2b01c0dbec90fca152052b06c47835ecdc270f49"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "c9b75a8b068a621d0f3b1aa7cba80a03f1669396a4dd06c39e7dfc854fa2917d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "bdcf82e1fbaf0885e5de6f58a52dec61c65f6129"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "d001cb0f3ea89b5907bd2b8891196726cf6eac9cb14d684a902e5118511423bd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "b04b94c4088232c1ff10e3536d0edb88eaa54ce4"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "c9b015c09c0b2cf249623449279b1c0545bff280e82efa4b95fc6dded081d80e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "acccdbed1a93f16a7dd172e26b1963a39bcc81bf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "23ff18906f32660857769945472a010f614a2f8cd1b5f16da78b408e939487b2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "88be2338f2937c05d94f9044d088463e8cf7b42b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f5b751ef7cbb4673b37a5ef6d6b2c49a40be1c8f5e003e773f99ae1f8ac11fbd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "6e8836ca7ab78f95617ec1124707d4752b4ca805"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "504525e06633a8e2f4f9d3c681d1194ecaa1fa68b217702592a364fec0664070"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "345bb4c1bab3f5fe5e6dde554fdff9863c8b9d0d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "936de01c6a9a051de8605e6ce2475ad30ef01d1031d44f123d01725417caa201"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "7276412fd3f7425928b32d6d5ac3fe29d0099b4a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a27f79b62cc438f200445a5d0b797e9d23396bd9739d87a2d9e381bce440c2d5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "987963619f21d7ab3f1acbbb5ec2ad8e3b585095"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d44a5d5ed2267684b490036ea992384945563cf1e807b9eeb9d96fefc6f9f849"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f2170cd1c5170a9b3a7c0c3fbf1b75f6c301a4a5"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "cee12e02895932f51df6a0b1dd126560b8f3cde939f0c4c1cee920954a82fb0b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "68d0974dc3e481638c47dad2b01d947433c0783a"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "ad8e5fc89b07a1273a37783138ec81019b949662c891b5f24a7511e23d0aa86a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "586eae02fcd62bcf23f2f655a01c04fa805922c1"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "de5f34526e349fb26c7537518ea886fddc9196e1ece9c0b5667c28668ef53bb0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "6f4c8bdb32f0b84d70320f63dd247cc73d830af4"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "fd19058442d3e2867e52c70c3a6e973a1d8bb15a656c5123e36a0282ebaf3a02"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "add2d03735f0475820bf1f9b6c71e52474167596"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "44b6e951b21bf68f9d67fb68acfd45cf012cbf4d003f6a8ea3eed922f08c20f8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "99288cc0d831f9f68b369eb93fed02bacfbb5045"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "0617cbd3c1fec89173622b57e24e83cd5596fa819633e15d46fa69394a0360bf"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v6.9.1+0/Perple_X.v6.9.1.x86_64-w64-mingw32-libgfortran5.tar.gz"
