[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "69b2cdb70f15dd082c74c1a887bef6dd3fbdfe18"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "280221ac494fdc4161d60e59c4c3b547bda2d5cf7121928aedd2decb172c1087"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "00e6129312baf13b572dd857d7994799fe55cf9d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e7859d8a39bb01bb8fc3072b878fba3dedce0594e541501a7e4b3365aae0ce5a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "a9d62b1fe9d273eca3255598ae0604625d34ff1f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "36d65098918c389ac87cc741e49eb17811396ca5b3fd8d5c4fb56f64dae422ce"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "978f1a8b0eb6250ddf1d7021bac9f5a8a15ec752"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9a5b52a48097e3dc0b180757b3234af9b2fc01d386d2a8eb195e9e029671a8f6"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "cf589035727bb8ab0ba78abcdcd985473cd77788"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "26bfe9dfd67023ca261bcb953fd059daba8ddc797b1f955212cf7b8782c29425"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "50f563f9960b06136f7f4f0d22d3cf0fae379831"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6c9fd8ec3fb7106a988b8a0e0041c93e28ff7d02d9bc5f381dff9eb049b1c48c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "0fc604b3ee721898a9cf72978d48ae02f7045808"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "102133a135c61fccef39e5a047a8c339f008529b384f5ee974acdb7373e93a70"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eafa1574d2a4b561db8e3b7d981eeffc9e34deda"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "aafa81a882a874f3d70eb0357d872d748a4bd0a17a91fdc9091dd15083b07b08"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "831cbec377aaa16681c031bdf9149381a31c487b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "b927eccc702f43766412406aa9ea43f8e6a8f84ddc1c0d91af95ecd4c3ec844a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd0d94d90087ca716f8441897ec6a03d8619926a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "88bad8c413ca025144f5fb70b1b1f2c3f107b279b8ae4b82cfeea05e9ba2c735"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f15d5d147ec25b31c333c7dae513472cdc83057"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "37f909aa8554f9e8c3a6aea45202e7bab00dc90778b50f639675e3fcfcf1087e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6f3d95399ee60eaff86bfbd271cc74d694e69aa4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5a8691162fa580fed2a0830a7018b9283edc030e555f8b1aca075efb5c78edd3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6292f0832dad5de2f2e66a4f7b6ad11fc705f1d8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8443d8698d303c1741324ecc0e0e2b068c3e8d21c1f2ebd1c2dfdf6eb0dbf626"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9f64a73360a047792bbbaca0321b1422fbc79aa9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "65e6d343ce8fc5132a31f6bd30a156ab97e0a4e070b8be5ecd3c3a176d85b2e3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "21ba95bf83a4b4b7a2b3a4c8ad18c530118887cc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fdda5eb8218113f1732b99d593bee7d145d7111c89b0355a65eef7f82ab7a126"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb2e8083248cda506bf9604d96eba5a0bb32ee92"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "251f3ae156ca256814e04ab9d1961a0cb357a6b8aa05d3b97668443ae185a325"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "225fa9e3fd289036c33d44f4bb5ff28a9e7109e7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "774f2869b57644367ade3bf5f5e882cc1ae2d97c4ab55c9d62efa3435d8cf232"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "901a5da500567fef105ad6f80465f25053a0222a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "eb0c6c634f6bcc7435e9d543d33a2f405c5488576ddf53dfa1a9f1c785d679eb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "155a4f580e23d470c09fb72f45d006792b0d2c64"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a34cc4f7fa4c68fc28734b80a6763007cb0cde4c1d2c51ed6f88fa088f40feea"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "2d309cdc0c91c76d0c48ab71f8dcc7356baa306c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ba1f71bf573c5c4cb24ba8ba6f9ef58c2eb423ecbec7d713e318ab223ae828c6"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "9f5f918d77693ac15ba626447305401d56d3d99a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "09669d9f96ad04ea302523b2b1f0fcfcfa120b1e7d97a86f28e16fb55ae8626b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "5b2620e19aa1fa2cdce011e9fafeed38805c5f92"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9df7cb30d13364f8cb989e09e05566a2b8ba73bcfb6810d3646953d43dfdd3e7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c8fe4a901689ad672c86203e1c8bcb3876ad4eae"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3eb0dd8f5517bee2ddd49af3565e2b985c36f28f97c053eeddbdf78322ca70f7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "5f48546c7da4d32496af287f975019ea48891ceb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "373579bda823fd3e8171423a09635bfa14f97bbcd1e0329fc2e58e2e8d7d0921"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "422897f0bc7269830cd0e4d1b87186fefe676582"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "1fa93f743491d8889125f4cd367dff116f7bac283bdecb9d182e061763e8171f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "a31970390ff6480383dc41e97d732fc3bc2a0ced"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "eccc69d3917c8214e9fe78316c55461cda4071b6f6337b640519d62c19b2488a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "2aa514a4746adda4032499dc57368f9e1e0a08fa"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "46dde0774eb3ec45a31232e0182a25bbacb8fd25034d71e9d9f79fa2e118fdef"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "a75bced87eb7cd231303f8d6f95ee0a12b208dee"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "83eaf77b5efed4e06e0796513f2116153ae662187bf449a09bb05ef9776ad449"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "e43fd7891933d543fed2a2dc4edc7711b4eea1d8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a5d74a3cd518fdf6a3bf042c4443eb0449644484186574add7dfa8ffb882dfa1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "b13f021568d7e04db9118c6e7c893989450b65f1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "eb0a912edbe6b34eeeed07ec0f4e9aea56d0045c98992437e223bc5c1ad05de4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "e143b6d898f92104a085dcc0255399bfc544e381"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fa019e2a2f2f37b020a0dfc1f7c674ad3cbff8602baa60075d0efc9f7865f8af"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "6bb22a678f31a539ee704dd4953760e86621b2f5"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "1f82dba214aef2534224d8102e2e5ef647860390fc36002d8075d230768dc852"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ff1ff7db2fe1b839292309c4f92d5dab5b7d21fd"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "77a1d1a8590a1ad9758b20e0c57a1b808fd918df474137bd4e42a96f77af041f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "9aa9813c01d45bf37b4adba03b9b923825d95cdb"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "dba36fdff3c6a425eedd6f60a0f78f263627e4ed0e67aebd54d59101da6098d3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "4b02dd7e3a4bf776222640c7f455df59264b55c9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7e06a6d74e5edf5990737c0c2096e71c621e68c2d9ce72f2ecec48780537fe16"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f23b9a12aaaf1de8ba1e885122cc372dca4b5dc4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "73954bf9cc758b23edf665a14b732ff82594cb3a7e086c03c300279e0165f623"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "4d2d569f5ea54272dd77dad65918e9a34af6dc46"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "073c15b210536830a273b7011adc62da7ae5cd3e083c4688ab5016a1f2579746"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ecfee4bf4e72d041466f8dd8698d4e9044bff2db"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "588f9cefba836166e61f3dd5f11eb934dfda32f3906e9858917c1881ff3685ed"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "97e9c9e1af2954c14ed60a3e4d69fb848dae13a3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a9bff8edbd150aa3cc3a862b584ed82ef569be3eb7ba02fd9f0754ec442a506d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "8c3e0dd4bc0df915628bb1af83180ec1f24c86dc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "34887417d08c2888f4ab31ebdf397ffc60ed8b2ac0873b97d85ddb9616f6999a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "2b73eb6d282a0eeb9b16e4086803887d3b5a5969"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "7fecf2ebbbba84fd64a6691fa4ac9717546c6652e6a714bcffbfb8346bed0c17"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "c2e286a14a132b56e7e53336d4022e4f87cbebb9"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "8067178ca22c5c793b1cb3c29ab0d2c01b023c39464c4e2bdfbab97466b592d5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "7c7aeec81b1a8d8e318c4b78f9a4317a78b2d5f8"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "0bb37122ebbaefc8190881a4e0ac5ef0ec91c7f1d54056a9d1c1ceea5a341379"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "6c9c0960f715bc2bf5920c8001a70d543f51cd4a"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "0922bd8dc7ac0ac143fb2d213f3e88515fee303a82076ed900cd5c2068bb5752"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "a2dfd6ce5901a50f6bbd26b8c751b61eec9536a3"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "ba253fc66fe72d43fed17be816356dc0b0c046be53df107cc249f2b3e645cd3e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "e807b7a5bc5ab35ba9cd404f3430e316b8c07e41"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "dffa58382210e91a7b9ce56bfc69f5df01ece0480b08f364b1b0496322cdc327"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.6+0/Perple_X.v7.1.6.x86_64-w64-mingw32-libgfortran5.tar.gz"
