[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "6be56612f55f417d587783e67259aef0365b1ab2"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "b808ecc08e8b04e82cc398383633789a3050397b15dbf70eede2b9e02c5a5642"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "ce1e1d7d4209a249d580df566e65939a2ba93004"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0285c2ea744664fcf44451b2a42a58341069fc774b28760af00d2977b7ad2aaf"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "ae584f71ca52c6b0db07a3a8a058b100ad7f65e0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6c1f0a1f50e401084b6141e705d3c4bf080928c2720b7afc0fbd707a214cd4a7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "ffc9339d1d27eeb883c7469b8b7ce95a44ced0db"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ab3c2964945c82cd360ec30314e63214c33d1793847b16522fb0534e59265919"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "1b4765b13d1b37054244c361e835e6a34b230dd2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "85cd461c63c5aa02033882d68795492daf78938e27223df181682ec0495cf605"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "3179facd3d3bbce72babf31ac445b9a674363111"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f1645e7c6475623365654482725372ef08baca0b4579856945089445c5dccfe1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "5a526d6e6a3ec30384fdf5da2c7f6848dada682d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "2b025585d2d3d4c66b4609be8608a9e499d4771a7435bdf9648cf655e14047a9"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6feae886583a0c4fbefc5dd44ac68db981ec9894"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4fcc0d40531b73274f4acc689ae1425bc59c2d2d93183ba6d6aeac5cc0e7d7cb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c028d976f10a76dbf2d25c588fb95433608f015d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4a4dbe296b45d86edf5b761309f1fa4ecbee44b45d2176676abed15be2dde46e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3323398a1c9c2c334e7b7cd1c6eeabf736b034f0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f1af9a63c24cbb40ba058addd0942924dafaf3daf65b66e99a47beff0a849299"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f4f6ffcb0b3136009098ec0f6eb961e03702013d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5a57deebfc305f82d856ec7f03078e278370b1ba85d2d24c7f3c924e302abff7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bed529b010b7ac1d79d8d991b5e271220aaaabd1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "bd965ec0a04090df3cc7364a6e083db4017df1918f980d95b48286b759b460f6"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0e4bdbcbb8d02c6423de6f803f034af4bbd708ec"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9b80884bd12d3bc9324da9badfb673726c8d0cedf98660ff1b79d77c0ca53223"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd424c5789331a95dca53d65677b7dda47d4b15d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "76eb82300a2c1fc76d033a5b15858bc1a788ad65a0abddf1966d31df24cce019"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b3876073352fc11e4230e8e899dbe2e72eb60fb6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c3f6e6d78a22e3cac15e13b15c0cd00aae4019b000bfe8584d0ccd24582bd79d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e424e4b2bd91000eafdf8726d2d10708a72c8879"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ee44c7bd92aa7df416af9cc079564208ac2dd9487f6c351d91c7e5d68c50dcf6"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0a0024427e6769891a2b27a787174a93b80e627"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a441f67c3f33f5d3b79c491828093cc5abff7e76ab38255e318035b5b2916e7e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef19a94fca8a0d1762c38b3a78ed406bae24001b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4ce569e0c35cd82a57975664a3e69bf8382c0a13ba8296e320ca66dd71010e55"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3c9e73b1a891902c701de9b636283c40d4a9ba07"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0ed0092438533e91d2eb3a3585f698238c0b9e8b775db787f4c0d94378e221e4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c49de74841a62719e42e324e8d5ff79ce30eda13"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "b7b72853be7fa151f188da80f96a2c2234a47332a5129412ee443e88b2bccc55"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "887081a3b3a20a8b0529a4aeecc158d12b338885"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4871afa70abbb5ea310f1c4395a1eba7adb1f12265133a9dfb19f9182212959a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "9e0bc8f5e51cb87b9faada4c4cdd332b911be58f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f7d3b032fb1cb7f3fe1ee9beaecfb36cd75e89dda8431d5b8f90f09954c8ebf8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "f4ddd5509c3ef061360c04592a3f52014bfbcf1e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "de7f1ad80c4e8b67bb9566936865b417c11f07fb6772c967bb899918dcad6b73"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "217283dcee17ed4a4770d20306052888078cba05"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "95174ff87afa857e632fe6d232ad86ad9ca5b1e5cbf88e6754eef425486c6b0c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "f7487d94763db5aa33a91c2f4fde792ba034a899"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5a70c4faea11ca4dd443433ce5310dea658f5633774b7e881b8bd567bfffe24e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "cb7c750523bf03245820f889e75a41df1e30e4a6"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "0cf1eb127d8c14b338ca1832ce12073199ec02a3633ca2401e0b8d0c87d2405f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "25250c2df62ac645f4d48d0987dbd23029db94b1"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "ffcc516f93a985542b85d41bf7bb63a7ec9d1ca3deb84c6e6658b54fb9cc9ae6"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "9b14e9488b9cf7a01a9591755bdd47168484b571"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "cff59d3f5b36975b2e8b84c9e11d7d2e2e0d79a18665782e9a796d5c629e5e11"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "a4fd891a64c27bc556be2e0c8bf8d74c6cefa1ec"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ec31c318ef5d9851d9d607fb44b06a0d1f12344353dc1f4cea68e1c45ffaccc3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "28be075cd6874de7c9369b700971ce69c3ec4209"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6a7fec7518040c7339b0567c88b1dc9f1e052d8762e10d771479df1f120585b0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "01ea6dd60f8380d14a0e24d2426096cdd87435bd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e9f8dcfe1d65c0289a5f86e3f3a69ae1c0874ee74f770d2fcc6e435200f2b484"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "798a2cf7ad7675f7652376b1507cf444631800ae"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "306b4b1f5451a1e5f1f1890fa4f99aaaf84f8e07cda92162c23eb892be5689f2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "140ea9641e56c5ce7f71caed5d9a894605d24cc5"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "22119ac7bd27fc203b947fa13a842874283ea6e75ef45aa10c4c427c4c4554cd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "b55bb5457fc956e450a12cd87cebe14d5ec3005e"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "cd8979fa04a1bcbc15e3c6a03af58bf1643952f487c8a48e833db73318258c25"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "a2c12190b91461c4d06eef6755ef3b3f0f8f7f03"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "763d30d4fea8de5d24e517cb2098818e15419c8780536680d7203d3441ddd4e8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "71079c85fdefdb0128ec384c381fd110462c1e57"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6914754dbe75f0792e4800c8f711be076f5eb09fe60ed9644fa3e36fb07ac6c9"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "b905bedccbde5738cd972e85bacbd872a19412a9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "089ff0a2704faa934d5696d0d8a4bb2c7a8846f32ebcfdbc7798abbc7cc1a6d3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "0da42f549661f469c70faa4f802c52cff2efb767"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "315c1cf318a4653e3c489f1c2b7fda84f8d2d3f314b499b666cf0af93e62eb90"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "b7bb9ac2c8c11a94c02284386245290b5592cb46"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f15e516ae57c29f50831d89af3e1e4a4def9f3d2279de5d9010ea6a88ceaef05"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "d1e2b99785f789e3c76cb9184673c900977e979a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e641d9367d73fac9f1dbe93369ffec0f2533a33dc2ef2924cf6643d9862b1115"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "0984c78c371580ce73191d0a49df586a76a40eae"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "a167066e60e102b6b3ebbea0b9f52fc0db4bb807315a120e7ed6978afee0d2f3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "84ed2715abd972957127692cd3304d7958ee5a29"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "65f6e6353fd144f4b4861c2136bcf1563d68178f9a61983e51a973a1c1b50e8d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "e2fc5bf22d4298965d89ab5e571065cfc51a417d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "2e3e103d6b3ce9cb0f6f6124cb8a80c9d4e23b13686c8b4d4b20676040cdcd6f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f45904835701f2cd9b826fdaf17390c9ae47a01c"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "e9b521d5f5b644d22c95edc8d85d4530cedc9d87e505d4a1502f989b6979344d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "2c8208fc0e4a2e723c9f184ba7c8ec6abc2df91f"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "c6f0ca685e4aa2d4aaddf2a5d14473d622ff0d46667ce1fa17375a6d68e6eaae"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "cc154fd508e742f661d507420b53f5792ff871cc"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "9ce90bde096a50c2378ac400b685050994a2fd6592e6ffabc584e2055fb5c703"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.4+0/Perple_X.v7.1.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
