[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "7128ef341405e7f28af2d7dccebc637f5f4d37b1"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "696927184b60d6a2d242ad8609bbd27c3868b39dc8003c808dbd45c721288a52"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "5ce4fcf649b87d25365ad35851a1b48fdcc1361c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6591a3d1f8616f39a1e58af77e0d466790bd588551cd37121265211540be11f2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "830a1d7a8b1e821e40fc9b04a41b030321361f66"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c2bc75ebc113af70e41319b3c2c44e3d80e2d29171ab3f656aee2a5694ed5dff"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "504330bfd64635e88c633b3040e04b11aae01bc9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e282643d9341a36caaf5f01ba5841935fa88c733cefce980708eead8a2c9fd47"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "969c228ac8e2e2b411c8f5b76f47a194039b5e5b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "524673f42e975c77518c60a2b82ea092287a629d122554162f331013c39d233e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "cd8e2b8e3c2b1e622d0b3b6b94d83b51dbfb01ab"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "604bf1e6df316f16be33420229bd9a430f8f970152aa0dcbb11a091243bca55a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "b6f4596db9603a6dbf1e14bb43abecffd86ad793"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d13e390faaa58222ad1293cee68dadbd9a2223da163ddfb98db3e64865667115"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "3c5c483f182e02339add0d192b0be0742fba2349"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "318267304d2a72651ff129368fd80d673867d60ff70b594a648ecafed4e787ab"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "b60c339dc9543f0e9873d9419ed98f65e09825e0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "43ac17fbb66636ff7bd110bf100c44945c8feb720d56a1b8cb806f8acf8ae5c7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "df6f23063aad1b0dd66676ca82ffe06fcfe31fb2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "b0bf17068376765c564e0358549552016384fcb186dc931236452d1bd94b5e83"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e96df959ee3a28779ce6f9b143b589b016ae9ab3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "931c4feee6c8d229a1415e19bb0baf82b9b971c82e43f62338737551eb8c674a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d6347bd1db123c69ba3552abd423f3101e891ef7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4fa1b936538bbd5eadb0ecc0ce3c79f39df7ab8b0b1a3b1788e91769e922e051"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "845039751073b8e3cdfe3e90ecf0fd9c2c69d66c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8d8aacca9a078a4284d65e9f9f8f7c49adc6408fc789568595964415fb3d1520"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ac6eab0c4af07d36c8763923bf76c732e5ad7749"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fcbef2801574163ed442f8c34d7eeedca5bc5d653d1541c7920630c48961b9b3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c87b513f286f0bf1bb577181222f62f789b85f5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d0dda4b2017ed33a5df166c1373df467e04bef8aff5f19afcbabd5e727070154"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "057fd4a6a8de8bd20dd0072cc0a1f646b3d4b62d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "bdca449829adb5f180c6b30111de428df1c9eaee3b2c4dd3f47f829970f2554f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1eefde24d8cb4bd649da4c14258947ca7928b8b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9829c86522e366d90be06d6420298bf76ef2922607c5c645bfa77edecadb51a5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "99e6ef0e4922e2127a0b8aa5822d561651d2501a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8763392564cbf73ab53fc81019a7590d8e0cd613038e5d75e06e0b6bd60f76a8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "57affc2e0218c6805e9175e55d4b067504ad06e3"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e2c438e170c8385afd6b0614b4e141b41018bf4858708e6d0c917c9f3dae0b65"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "40413cb7b2d4210587fe4d18921aa434f1863a46"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "65a5e3942cd59098badf0e658a9262bd8772060c31e3edef6575a3e81aa2fd19"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "779f8fc00b66b1b406f985643b2bc03711640a15"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9de853c65c5b978ea030c66684526218a9301c09b58050c6d245628ba0d0566f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "a4593c0896938b0224013b125401b7223f77ebf2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ab0e05bd20248fa41179596fd4386ee1591897e8918179340c08b70d1d8b2a94"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "d8d3ffda5a48e804e9292743d4cc056fe88a6af2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9a80fb9d35ac0c026afba35a7dc3aeac7854d1029c7e4025767daf6d5107b2ae"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "b4d7fbdb244b5d3ac08aebd0a53ad0d832557bd4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8deab6aa6d868ea71f6a36c1bd624e51ca94fab7e367717039d89338ca326a6f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "30fdeb078680eb14d60ded485ce8883121f8110c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "467bfaad46bf735065ae3647fce5e3ae7996edc41df4aec248218bdcf625b0dc"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "d88270fc36bed75c2748eb6d287abe3b7669d056"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "aa8e3f943820cb57d474f4f251ddcd18ec775ff5fd7ec4e688c0a9073bceeccd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "9609a2809382a982f98c2f17e66cb9637fea1011"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "2d1e22fc1b2093bbb1bdebb337716e97697aa98f25443bc1fb442e3f9d833818"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "7a6974d35a06e5179532dbc212a3ae144e06bef8"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "bfd577df8200477f9b861ca2ea3e418872fdeb8d4a7ad556caeaa3285c37d3ca"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "ec9e364edf5f50c90c657dcd086bc85a0dd10677"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "d442045a338aa4ceb36cf6683ace9de97a1f98c6fd719eb5175cfdb4b053dccd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "660f4f178d1e3e26abe90f086b216a1a39d7f8e7"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "add7a7c75aad600e503e7f0906d0177e4036848f266556ac3dfa2361430ae88b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "802811e1df6fa39f7399b60568b982474c843cb9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fcf75fbc3cb8fcc4fcd5609dde7a7f56ce2543d6ed19ecb2149748787f7e487a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "d2b5733c23614052cf4d2e387449b26664129257"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "4f9d5145d73a25f4610b852199a122174cbe91279a02495698087983b60249c0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "e2e94fd89c4d56c2b4917979cbdbd7efc359e2a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f8dba205ed19b262f4557b25773142cab6621ffdde6ebdbaab3b36638ba98c44"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "efe2b14a95ebacb6cbcf42aff9a941c1a99f0229"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "cb337b5b862edf349b1c053509039b4b5360e1b04532ddabac686a2e5dc31a64"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "5b84e3d20cade5bb9b26d7663c15c5a316f4dff6"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "66d411ca8badde4ced8d0d8d2e5790f594914a9a6a593f96fc18d0465eaefe4c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "3319ccb427774b787d505dff3708b954d09f9c51"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "dba731214661ebe84b3c8ea674425c16a9f4f72a3b506f8fdd1abad89f94d3db"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "39bfe43eb99d61d294c6ed319c7f658376015a7d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f9cc48f021792e05807f841af2b2d6867e0a714479d25c2c28e032ee898f82d5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ad77adbe300da0f41f012b2cb21a0c2bbf001d8c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5802f125d7ea2747882a3004500f28e23071925329bad9a1996d00e1aab75277"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "bb6750ae60a6adb2910d5c28468cab86508e7b21"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "2048cdb53b0d4a86e37cb56ae4f5eda69397a1a9e5251a282d72f302d7360938"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "01acc981ab58c82d14109f0df4555f1edf15b491"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7e39415f2be01d011ed0f0d4c4fc93a6e147ef2bf349ba34ac1c7b0cf1c35314"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "da1f8efef9e4f6988b70620c658290dc840c8b2d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "72d44ef920ebc7aa9a5cefafe12f55c32eebf8631a2463ff0b017474a2adf386"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "5f4decd71139d50e52ff17ef4a86aa815d98fe08"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "69855f5b0b35cbff4fbfd4d2c81e4cfe6dfa86afe5fe098bf54b715d70b4a8e1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "c88953db17f554a49366308df518c108ee0ac47f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "bb67796e26366e9ac69ced35e03232c4bf50513301ce3ef4b809a9d9274c2699"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "05bdd392d2d4cc89293a3b42ea5fca0f45f802c2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "2c2bcda80b79a598126530032a3b9a0676e2b9ba85fb3d3c9d0260f47eaf0069"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "7de02cd0ed413772712923156f37e2a66abac111"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "0a846cf515bd153907bd38cfc4a7f0d768b741714966f15a61f8d0a640233805"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "72af97c46818ba35d59414e175af58567a5cd20d"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "8813a714da776e60b03cba724b745d77222cdd5d3878978fbc6eab1124624e65"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "4cdc60db6e63078204653e458ff4114c27d18a5b"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "a3a2feb9af7c4a4596f3281149ceff965aaf376650de5053500bcd70b856f503"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "67064f127cb8d6c421f0a369220db4d2971c8d70"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "3ee39822c34f1bb1da8941fa6c551e9004f4325756a663c6558284675595665b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.9+0/Perple_X.v7.1.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
