[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "35c59e0d84aa3c07ee3d16cb7944cb623dab0297"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "abbbdf31d741edc349cd851320ae716003625b8c5404a28209b03b54c5c008d1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "435eda80aac153e7a7b30a8d7615445faa307edf"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7561c6020ce239cfb7f5fa508f2de8ce0b830dd13cddf7fde64a9ae4f40cf1c2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "66282fbe18b8e7bb0865bfd6cf60146d7ee21920"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "76fb86d82e8bd84cc8d2cacffd150b772344696af48ac09923b9e9c7eb8f0714"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "d6eaf2f10a3c04e6cdc90d166825a05cd6d169bf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ba8c1fdd5d18a50d4d643d84130f25d22d3359e555c591f3a4d4bea64afd7b54"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "1c8dcf5a820134c9ece2bc2f28e8f193447a36c6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fe119c805c6e53f95281d53becb4d7a0e1229de5111e110850eee35d7d4ed784"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "4afe4ba5d31588bcf5df4fc0f9683bcb92eab37e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "330aba95fe82d74171f18a29d515d03f1fb397c52952aace65fe0f7a5ce2e556"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "d8d718c6da9fa31eead42bb4409f9e89b93df12e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "afdcc9a071f9e8f678364c49f4ef4564aaf8b1e420e85c4b9261439852cf0b2d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "ca361c9558331446e6cf50b13120c3f95d5c1dad"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "e8a8428c28dcdd5fb8356affbe5a3e035312ba6410de7fda2e34457d20a77a51"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "adde55020fc2b1769825e1c5618a5a8647cc4a32"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "29c9080dd7a933e82c168ccfb48c3a0fc7554b6fa291d95ffda1c4a47c956a19"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d1d855ade14c9507043ea48fd5506fa1a1b2b28f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7a0f073905743fcb7d02246b2f3c2dbc5e9a0df75412c7e9e72b9838ae559f05"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "526ab1295f219667bfa5115e0cbcc7d4834d5c6c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a0efcb64cedce12050894de1cea178fa694018c2c540fc0334b4f639b321334e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ffba49950c43b50813cc17e0d23b78f8e87b41a9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7a551748324d3d6312fbf459545bcba7f184dac930b725ac6cccd859208b7524"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e33d82dd669917a318571f8d086c248e23a7e2d2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c0af79d6614a821ab179a490026d23d02c98148c1f3beb6c170efd05bf01da99"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c903b11218dfc2a7beb820dd95394df61fbb1b26"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "93a0384b39a3875f86eb2e3300012c5660e4ab5e97492556c9809acee43aa875"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ce480e891a940ac44d092f7331279fd220b0d21"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "601e2b66b04ee8892831a01910511e18440bf0d499198c60be0b815a67b69e11"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "759b944d4e6ae75b9a14bf9f0cfb5acdfbed4ae6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "65cd422139751856d25df8d6f1784e3d45f0773c56d69a6b70af630c3d975a41"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b2623967e11cb7ef3963d30d587bec915f008a78"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "954099839d3be99c5dab60b51d3efe4cad5b697f55bd63c2d4c8e58c96e078e2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db2434cd6951e2dd867b80f132d7355e55818ced"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "345895597de2a1d547d82dfa9d7a03e9dd1da792fe60cd5bd10b8b697aa6c296"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "77ad0f931e0dbcf42982716c6b0ffd5198d7eb5b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "784c1f04223c420ffae79f1a2dc11acb7b5b509b4c7946e89c7d9fe10c98bdcc"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08968967f518bb9781c845d5a117e5a70df4ccb8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5102b92fa5f3df92e3ace58ec44ce1a02ea5efc8f9f2ffa1c6c26f0eb074abbd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4eed64574b44a0333bdc0d557d48dd8b58609feb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "cd2cda71eb759f8a5f1f951775f70fa3c39126db72c615145918cc37d1491252"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "1dfb40840aa7e46b2e8ed91207be30ce40c8aaf5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "449000a12da63bedb8e75112c3956e6e8b587fb4a4c7cea364035ae64f49ab0d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "2e9c840ecce4ee73bb6793a1d376ea9e57318069"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3827bc81e5d6c994ec4269956968b5be2fd886dd9c1604a47d11987373733d93"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "f1a9de3c6b8d9f09365414fe9420d9dc80e5e74e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3942b33bbf9ba39e9409c5058538aa748c308eef5aa675b7be218f48e1371396"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "d796926bcb700ec9f43f159ae08d42bb75a61e26"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ad1818735591036eb572ef719af25ee6f697fc343566d91c53adb0c3d5f5ddab"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "0b9de34831ad5748a99f673c56727d4a1bca1b64"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "72792e0a555e59d1788d3cb600d02ca360ae9b40d4063f9f4efc56ec2452d945"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "06154bc3a5cd11c9e44da677cb435183e17ef5e7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5b977121d85c49c0d7800d8f69ec2383ffe6445a55628153ef997c0c12ce4932"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "06652265833577790ec664803824efc3ee951055"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "4121e76b2424632ed6fe991c58bcff7b311efa99967d0afd924473b0d1a329f7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "4e8effa1acc9c9f989c6d87fa49db0d9c0aa783d"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "ece0f04a490c579ab85f6a95b47fd97ce9fa707acb7ddf66c29ce48e34e5a4d2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c5fcc62f316b659bdf065829cafcd1cddfeb051f"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "4627bb757b1296284dd1b6e17f9c318e982bfe9586d9790b3d4329dc9461f04d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "b46aaa42518cd9b8d4f3316a72f350ceb76814b1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9cea37b833d75fc0453b439442430aa6e98a31f000e83dcf9d30fa351b75c2b1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "01747eb60e330ca18191f54ec873aa42fc3fa47c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fce4e9301189a3d1ef1f242ee3e4c9c2d5413d2757f1299406e420ee46aa0ba0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "bb066097cb5df611ec0c0470bee11ce704fd7253"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "61ac69390fbd888b06fdc5c9beb1b68cec7c12055e8ac6a1a783b4f80d2f8ca9"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ceef5a1f0e316cd22fb80801f8a05bf3cd97f924"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "9a3e327348e811dcd744cb750f54f33095da996839e132a8cc98d3e94a0f027e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "3836b28127ca23429b8d4c2cb7b9463b65ea0db1"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "4fcc05e2e42ccd18d814ea8111764920e69dbc4ce0cd8364d5df38285464037a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "a39d82aaf070469e25ef677ef5b33aaec8b81ad0"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "a45a356ba7da89feae6e717f2c9ad60e7005c7acaf40cb8aa613fc8c2a4e92e0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "60a7ce9785c0c9b65b4e5cfd627f64ece6279799"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d7c727444e9fec04448aa7f5fa79086f30cb3cd4ce2e40da65454286915e4bd2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "57c9791175a02e70856e4ec191a19594041fe3f5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0417e73e36c8b97f34b9a6eabc4ce9be0b578188907e17cab6142d4eb84fef37"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "153a4e58fd2c454d2fca506b9ff97ea94fa65e85"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f648e80e4dc74ca3d3b000f2ae10d9447cbd2dbc48b54226689094d805a60dfb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "50046f4edf26b549504cb6108e5ab38a0111e060"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "48d017048bb457808830864d21ee23ad15fe3a8833483c3e85d95420138915ab"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "0a84e959f09c674fea8fb3322446f21e1deacd29"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "1a7ac550da4dbb441fbfb6c7ce4e98355ab16e57ed5a1137ae537fd773da460b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ae6f58ecf6287d056b93a3dffa841aea26a02e17"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "1f520d52e5fd069e400ff4af7b76cbc597abec2a6b000c9e153694e473474d40"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "71ecc3839b061d43a0be427ae9e06c10df95b7bc"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "68ad0fee2c7938078aaa2a0192a20e7b686dc7bc5ff7a088b17b26069c438f32"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "122e04bff73b6fd9819c5d46fb8a77ca7700eaf1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "1890c4bc2db5169f89486adc450330ffb66a003679742f9f61576ef92085e8c7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "4a18ec667c76b569a6f893c2a18f7c1b65cde341"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "f1e0dd24bf979800bafc1b09fa3fd0014308ab4b264a9d5dc46a7de2316b5091"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "36d30deaaecf4e4633852ab6099bc9ea096e287c"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "3b29fd13bf8e6332894667385b16b0fbc1f69f997d6eb164d2dd03c250a89416"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "a9ad7459979485cb2513a2716f15ec80ac75105c"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "20cc7de8f8f59bf4ec441874dab21497d447b47ebee7276846d27de3f959713f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "0002b8aed9d098c02fed88651266fb44c97fe730"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "920263ada8397148af15786ca32921a90d921a11bd53f7f34166d3a7b065650f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.1.8+0/Perple_X.v7.1.8.x86_64-w64-mingw32-libgfortran5.tar.gz"
