[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "ddd3688ec7f250670e6761b5e5b6a91ed59aeedf"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "2cb634e7b56dec9ca701c3c00cf529f85b0ad29b4449a64d2f3a94007f4c83dd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "4984a00fb0d43428a49c6602bd2e8f7d41194d76"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6dc6c9c09f5cf0447ddc2d7f5e9533eb6580399c051a48ffbd96caca3e6304a3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "62ad35f6f8a950cd1415f37855c629c510fa9bbe"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8fae1b8c670db3503b82e944c1cc0842cd5d01d461b9bc3183e9b42b5567e22d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "fdd4c1afc8d389e3192c9205dd8121381807b78c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "b746d66b9f926b4ca5fec11ec430e569774666cf937a39f2e6446441aba5c79c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "d0a637c635bbd58cb18b24ad87efdabf7f578bad"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "72ad86a6c7fd92fbb9977eda13a2b88503fe517dc4b8aaf3a7129a393f8ac86f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "0184c6abb183b64fd8da2379a4beacc71431eae2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "46e690336f0b052102132eb75da55a7bb194b8c69c5effedee4fa65ffc270305"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "be8a5e6e42b057d29f8c16a509f1d7af3d3d9ec5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6441a37693311626ada43c58fea1ff5a7bea886bf4bdf869c3db21f0a7935681"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6e36b2ac32344039cdbc8e0e1e88044bfd55234"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "243b0fc2fe4a0144e3460f6d3ea6e9bb65d7a8956b89f6c20f7e251ce06a495e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1fd4ba69b4ecd277384a34b19dbf8716659115c7"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3cf38563a78c0aa3781bcd33f516fdb993de3c6b4b9b4ecac2e8a6075b47fd4c"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "720ed8408b94bca558735a79adea578f3d4a3ca0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "dba2fd56b56b598f5ec93e9c68b1864b94c11f7d7c767b05d80a4a6e79b61d0d"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d238f87938307d7339b2f9acc4fdefd1f096cfb4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "daa460cd19ff461762fd603486796117616b9faf1bd8496634be8b33fabc8c38"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ae40638b1bfcf9bac08c45f8fef5759662bc578"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e4c66ab3dc6a9f51ec49b9c02362e868720a4cb23142d6748626918531cb7934"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "483da34ee113763229a8ffead80e38ad92fccc64"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9c0b4a8ec674740c33c7518059ace04a2532387bb746458f05be7f54139e6a45"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "439ce9438d86280cc79f08a89d5e3bff2fad1cd1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0b264358cbe90c2b3166f155f716ca8fd7f82fdc4b30809dca4899518bf70ea4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "824a839051da9a482363aacb77bd80cb7c1c4082"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "69c398e9861905706f0a6877d120bac44dfe4478edbea8e9977ecbe662c880cc"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ee83e4bd9a2653850418b4ce62bcf97849d6d5db"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "2b873306236bf06f950e14bd49646646ed6204ddb2592837a90ee02b78fe323f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe158b7ea82f06119bf6b96a2900c4b9f5c50f95"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "53d3705655cf3a26bd4f0d8470c04c2dce733daf74d772fcf58580e2b3b20018"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2cfa6031f417ced8da9906217509464f06ecf56"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "9b74755419768687803b7b5da88d560b42f2a280254bd7853ff157bd08bbe92a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "15b68ecc32bcfe1f3c0b0c843413f11e7d2d9082"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "08a623000c3dbb70817a9af6db0ec140cda65a94786304f9bc0ffe1144223063"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "fad4715f098ae0c160d92431fadf025d7586511f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "37ce6a8290f8483752fd0ee977a68947caed341f926cd4e8215955e5aed97b94"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "75ed1d9613f96522d90a28e0b3f5625865d91567"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f1cf8b97cbe0987c74cf4b762b52580196fcd9be8ac614e7736ccefdeb68e1f7"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "643a064f7e32c2454093ce92aca58f9afa724c32"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6caea01e36f6fe6feb7707fceb6c241861598c14f4ab7f7a2fac3ccbdd006bcb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "6881b4a4007e689bd593de02f58f198d642f8819"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "fc90f4390b6bc998f9e136de5c6b6764c07864fc6d2d0b4c7e6a6ae6c42f0b89"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "69b299248435cb8f861b8dd09994ec6c98756303"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "8f030ad748eb5f58c7abb750d9f31360ddc9558279fcec7a85e200c7370b19e8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "a2cf27cdb7defdadd2c5762f6be0f4af06a4a625"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "82287459a262cccf36f210e2cd5c4584c23c8cfe88130e4fb3e9105358bdf142"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c443de1668bc60ee7b1fc395fca16e28b54cd823"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "b9c88f0c1d65059ce926fdefa2de78cb3e435f27c009b8d9875e1ac4fd2ed5e2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "35aa11b8e4c94b96599834ffc93488004eb1f266"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "b78993d54e49a840519b461cf68047f7037af95d2deb09d4ba622f9213fc7a1a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "3fb5328d85dda4f21ed7636bd7f9c16d467dd84b"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "ba08cdff19dc57a889e434b2772495121658cfd5900fb00ab35765d819a9fa08"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "3a68b40f9f183c55717775f9ca6d4c809e6a490f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a66d5a66982d51e451a7888ef51e9d33a57919dea7ae47c6092bc17d4da6c309"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "3a1c53dde8c96ac55589e2dd178bde5b57e948e6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "35c6ab78d978b9c52f0853599024033f4987afb9722efd8fecfff0943c49c7ed"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "e0c860f39a50c397d77b8711be4d7f4d0e81b275"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "34e9704d7898b99a4c7eae11ba455648c8438f6d63cea113792f7ba3b49d2de4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "eb3addf18d6fa44a003c72439e7d636b51b504d8"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "06cc77a09f6ac33b84626f073b0480082703ad1c8961fd0f921c9871aa56a939"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "be75b8bd236f7d71765e800278697db041cea80c"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "2fae2a4ec20dc08039562056fdde0f59ae820f46d71c43bc960ba14adb901337"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "be6560d350d27bec8643b28ace2ab837b53d0b66"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "c8f77d4d96725d0e635669adab1e4bfd81fac26429788760432154ec2be00a42"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "02d951a0362e7cb405982abefd7044d6882c8fd7"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a0a6fb0e5b11a05c80d0fbc232e0f0bec8b6b990785f7f378386443767a4daa8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "a7874eaef5a5eba206e294e4ce30d6e781bcf2af"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "dc70c892340d0fa89b87a14d8b24089a603a2516ecb4286f47e7327ab32b74ef"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "d4c5cfa3166fdf36edc54c8cbd3e38aaf256193e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "29892ddb7a1f0065b4019c0bc740ed9e75a51988aa044a3aaa77fa7ebe0252dd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "d5e4bb28ba7409f27e11087fd371c58e91f30bba"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6a2f461212d8b358364598d0414789dd13c75085156acde1a5f5c163c9c59a36"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "99b64f3e4a90b3e882fc2da8c6307c3b76252f64"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "2373998958a7ea61bf16061ad410404c29b3278f412af351ba0410dbaac2098a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "bc730c78b20ce25ce9dec20a6d646baa79a0c8e8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c82f605503ce6d752cff5e2b86183e3fe7bf92919a2feba818f85cd02c32d510"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "dd4ccfd3d32c1121fe005e209167b85139ba2b5a"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "dbc71e76f9bc0f0fd8e4a348e12ce16c2fc795bec63d131a91b88ed68832abfb"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f6e68a799c2faca274430905edc46a9e9fa391c7"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "769b28288bc432856f579fde6f5612ed1e8b7df4c6ac3f28d5edb45256e8c188"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "2967f2f861bcb064d8666c820fea88c7c716b7ce"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "83ea93f8bdc65d904443f49ff070bc311c5284f02ce66016d2308bee73ed8b7e"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "6c241f6a891cb718e895a84af6d06d9939ee7563"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "f5ecc875ac1f13fcffc609931e2fe24e548ae34a9545846224486a2befa15cd1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "516390c15b39e99f5edd83a72b67a7e7c9c66065"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "7950af7fa956efa88d0ba7f963dd1cea336690e1a9a3e8eb45e350355826cf87"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "7c1e5b02c4a9710fa9c28f0e8045909fc81af768"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "a1de15050ae7da1f9c29f17f6dda64ce0b5d1be276afb1f6d7c7cfb24c9b5f81"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.5+0/Perple_X.v7.0.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
