[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "9d7842d15c5c8c3aa6dc9ff3f359dd31e3e12c9e"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "86fb2c5fb81cc524d784be8ee790be82e4c43d10757f41c95a4559f7d699e189"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "eca509f7baa56af7f62973138fa6d1bb18087fef"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3f496badd7e1e79304ef1d141d81d4c4d35872ebca0aa06fcf6304412b534db8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "14cd238f8404f1f5ce849eab877d785f2c903d4d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "3247cf25da46fc3ba6b9b55b50c77b7328a8f6af6e3d6cf07c7d5c024e783029"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "cd05428a0249bd51429d025be164e49c65480595"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "b61cfcb47e14169d725179aac334a21afd96ef196ce72e48df5c2267643f2a64"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "282a17579b93791cb9ee21ffc4543750c780c207"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "49a4f421c58640974ef1e70beadfaca0addca58c6b3da283b23c727027a34bff"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "2e6a73293218a5bd24534c6f54ea01f395b4c569"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "98bba74ee9135099283b2c7596ec0c3ec6d7069f635f594d003339eb4ac65bc4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "aarch64"
git-tree-sha1 = "e7e6150098a05d858c97c7c31f7527eb95634648"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ce15d406c4fb8ed2a09f97d63b311a944b973f4bc2ba2782a26c7884a5babea3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b6197f04fca3a612ccae6b010880a2ebb42f22b3"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "6752aa1b0866fd3be5a2afd5eabe78d2e67e2a02623efa4b2b8e717705212a29"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "101787e969065f58763221d08d4c0307b7b6c2eb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "57920ab355b789878a8d2f669d344c11103a89ce2c36e4d7169bb99486f65b94"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0327e53da7e2b68e7648deb8db519d2a5b0e8fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a776e46eaaf6e801d9fa005ee69d6d2c30e59d5a0e297cce7c023faa74d8cc38"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1cbe5778e393f4aa0e86bdc7934895721c2b198c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "48f4c220fabe521b0460459d5981ddb86e0562a75cd3b67a1f4ed8e9dd849cfd"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "39c1f415de009c3e1a4a8eee7f83ed7512e6b5ee"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "293334171f317bd2e3d1fac163c9b9a74328ab7179c7af9750419dcf8466fcc5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3763843316e7f0c4c9e2ae33565357b9550cb95a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "e130e1d55a3993e49ae2b3401f7ed62094bea0548b47d5c082886d07f1fc22d4"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d52e5817a08918087b0821c97796b4a03da3cbd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "a2249d4abf805e51d6dc0290debb8784afedf65292377f3ac25b2ca5c9b37bff"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d45033a60388f8425c85b2b9688251b5d4c2f0c0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "07e31337e3e9e2672577afa31a8685f91c970e8790cff0f02d883ef8a4852269"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7d5ed1b36125082c7411ca7fca647b240313e307"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7c61879158784244cdeb2ea1fbf414ea3b62e817300626b3ac59e8a199f11111"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "009a754d435d5f556d5b992d608395aee3fd1f1e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5d7d9bdef96d8d8daf2bdfbcccb2a2010d816864f8d801899c5f71719a17958b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cd286b1e0e892deb2c7ca655e58eed1b96590f1d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "32844f48e1314addafd7813e49992669fe67b43dc97eb902715f79a8690e549b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Perple_X]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc04c1f9572f77d6344b78626a2deb321536c649"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0e9bcd96ddda27058abb10e3e4a7a9d60d1cce20ce9477205e06f27424fc81b5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "c0f97d7c2ea2c5b75e7e648ee3d956fdb5462811"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "ca18f73d2e0c23882c5d00b470410092c830c5080a15556090b8092b1bf4ced3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "a9587c75c0384d46e44da56c071b7161b649bd0a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "91e2921b268dcd3c8c8537917126c582fce71506353c813f4078c2718e78d6b5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "84a2d0c8c148e85943f382ea42ec291c0d2941f1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7dd0f7522b7ed71375406141cec5b0723b316c8c33273284b5781a9405c5cca8"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "b6c742ab1c79cdb5cf9c1c44b3a05ca1ba7b3f14"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "47c8fe42ce667334ff6adec0951e5103c13af5a24458b7c4245962f6284810d9"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "692cdba1cb6ff95bcdc507da2869c6ac4b04106c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "f7399e152828209da2a2cb26a5d2b54ab91b63e6f2bba5235c3e5b8d4110e8ad"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "90998b8960956d2ca88bae84b99bfb08cf204982"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "32d5d7cf20844a050cf451041ac5ba00abfb85fd45937140a1e81ef8c153e7ce"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "3204cfe7202952a8fcb401587e753f0ae5def2bc"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "9250b81be6a1a110c2005432ed1e3705584d09d0b7fd530cf157b07a2fc71566"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "29b4e0f6b530a25165805fa2be3b4c55dc04d752"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "091cd3d66c944f4e38ea7eb73effca86c6b9f2099ceb8ce2b63b502491716e61"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "i686"
git-tree-sha1 = "4f7fc344e6042b0d1a90a7eb6ced1146af32f230"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "53afbfb38cccd3549fa52890dccd83666f1e800f1c082cca7d179a85b54cb20b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "3d78e8313becd450d8e6eaf549f1eaecf9e9a782"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "459a7c13ddc686c58e86a0cbe81398cba0c860213430f7345ee98d6180f29b5b"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "84820da23200cc540f6dd5853feb7126baefc6fb"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "d2c0598297b0eddf84e6bcb1c499c949b756f3f16be2b6112c5562363b508ef5"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "powerpc64le"
git-tree-sha1 = "f3a56b942ddde15e06ce8e18f7e1505742ab849f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "2e54a0f408699c8c5c6c0b3e4213bb8315b2cb06e9d7a65725584dcee4f593d1"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "4b485b111999403258ae92cd7a036cbf687615c5"
libgfortran_version = "3.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "e2f07f2e1dfd349d526886f455dc9c956db550b9efba53e077ce119b3573b932"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "325183586ed027a85ee06bf51176a02bfa813e5f"
libgfortran_version = "4.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "663e485c7df3663b1092f9c239cf72a71301e66d208872b5b3de7eca30342c1a"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "8be09b342f6ab3ea7ab33b111b5c19a0155c34f7"
libgfortran_version = "5.0.0"
os = "macos"

    [[Perple_X.download]]
    sha256 = "942d88a9c7cb4ccbb7e7a88498edc729608f1ececd414c1e914a13001d49da94"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "a439bffa7d37c93221c92dabb5825d2c415c3465"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "475f2a9e83110261878b538a6db2d98d487bd638dfb375ccf11061fe74a55733"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "51e62955d367b7a5f450bf8d7b587dd02b2bfbff"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "c10dc1bb428fa36cafd5c12580b1c847f777fcfba120fee6eab7a0b83a6debba"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "177a1a7e76f53c0efa830b504d6bcedae619e015"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "0c7ffb3306a9dce2cb6de4f722c01c587fc8e6e6d573623ca46775272189693f"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "83e1e0e06155708908112781de24b3bfdd544a68"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5ba9e4a92768862a9f4afcc41272e73a215dac77a152a0297cfca44a954346a3"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "19f20f42b197f0f344488d825db75a01e2c105ef"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "5dfe27fef0795cb56a70fb3a0e20b9cbd56e7eb4e386fbc71af7cabbe4b60db0"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "e5df0010dcaf1c85dfc9b8a5121e9f0c360e66c8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Perple_X.download]]
    sha256 = "7b9dbbb225d43534521059b213eedd6f89c2f2e86cb198661a4cb0dcf3f1cce2"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f1ad6f4de779947825bda40193eee9713353561c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "a20d8ada97fcf9e0a3246843852be1eb495fd6b78b482740c7171b38fbe74f85"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "0b2da18b64ad0e426ec236575895a1d195add281"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "e8e9569d61e8ad70e01e980d8ae0e0c416be941a0ffe0af39f36a5f585173b59"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ada19b41efcff9fb69044e842ea86eaaf242eb2d"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Perple_X.download]]
    sha256 = "c589aaa12943a8f90c837dd27664b2fba3977b8dc501cb805b9f1e299c1ca941"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f5d832acbaea1587e0bfdc6b5865256dad21efea"
libgfortran_version = "3.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "97761d69f1e79515a2072db82a7822d2c4230f4e04575ed28e49e1468f0645dc"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "f30a3c5507ad42ac0b7b8d53856f4dc5991796a8"
libgfortran_version = "4.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "155c8f23054d4bfc6d6a7ed0e9ac12399e7f059b4dbd365db4d540a20eec6750"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Perple_X]]
arch = "x86_64"
git-tree-sha1 = "ec1b283e8ba40fb7ffc7f6fccb09aa567ca46f6a"
libgfortran_version = "5.0.0"
os = "windows"

    [[Perple_X.download]]
    sha256 = "f0ed75844e6f1d1caed8459ecc9ce0bfe649a471a2ed61b316b8c384df7b4d51"
    url = "https://github.com/JuliaBinaryWrappers/Perple_X_jll.jl/releases/download/Perple_X-v7.0.0+0/Perple_X.v7.0.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
