# Autogenerated wrapper script for Perple_X_jll for i686-w64-mingw32-libgfortran3
export MC_fit, actcor, build, convex, ctransf, fluids, frendly, libMC_fit, libactcor, libbuild, libconvex, libctransf, libfluids, libfrendly, libmeemum, libpspts, libpssect, libpstable, libpsvdraw, libpt2curv, libvertex, libwerami, meemum, pspts, pssect, pstable, psvdraw, pt2curv, vertex, werami

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Perple_X")
JLLWrappers.@declare_library_product(libMC_fit, "libMC_fit.dll")
JLLWrappers.@declare_library_product(libactcor, "libactcor.dll")
JLLWrappers.@declare_library_product(libbuild, "libbuild.dll")
JLLWrappers.@declare_library_product(libconvex, "libconvex.dll")
JLLWrappers.@declare_library_product(libctransf, "libctransf.dll")
JLLWrappers.@declare_library_product(libfluids, "libfluids.dll")
JLLWrappers.@declare_library_product(libfrendly, "libfrendly.dll")
JLLWrappers.@declare_library_product(libmeemum, "libmeemum.dll")
JLLWrappers.@declare_library_product(libpspts, "libpspts.dll")
JLLWrappers.@declare_library_product(libpssect, "libpssect.dll")
JLLWrappers.@declare_library_product(libpstable, "libpstable.dll")
JLLWrappers.@declare_library_product(libpsvdraw, "libpsvdraw.dll")
JLLWrappers.@declare_library_product(libpt2curv, "libpt2curv.dll")
JLLWrappers.@declare_library_product(libvertex, "libvertex.dll")
JLLWrappers.@declare_library_product(libwerami, "libwerami.dll")
JLLWrappers.@declare_executable_product(MC_fit)
JLLWrappers.@declare_executable_product(actcor)
JLLWrappers.@declare_executable_product(build)
JLLWrappers.@declare_executable_product(convex)
JLLWrappers.@declare_executable_product(ctransf)
JLLWrappers.@declare_executable_product(fluids)
JLLWrappers.@declare_executable_product(frendly)
JLLWrappers.@declare_executable_product(meemum)
JLLWrappers.@declare_executable_product(pspts)
JLLWrappers.@declare_executable_product(pssect)
JLLWrappers.@declare_executable_product(pstable)
JLLWrappers.@declare_executable_product(psvdraw)
JLLWrappers.@declare_executable_product(pt2curv)
JLLWrappers.@declare_executable_product(vertex)
JLLWrappers.@declare_executable_product(werami)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libMC_fit,
        "bin\\libMC_fit.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libactcor,
        "bin\\libactcor.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbuild,
        "bin\\libbuild.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconvex,
        "bin\\libconvex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libctransf,
        "bin\\libctransf.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfluids,
        "bin\\libfluids.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfrendly,
        "bin\\libfrendly.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmeemum,
        "bin\\libmeemum.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpspts,
        "bin\\libpspts.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpssect,
        "bin\\libpssect.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpstable,
        "bin\\libpstable.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpsvdraw,
        "bin\\libpsvdraw.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpt2curv,
        "bin\\libpt2curv.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvertex,
        "bin\\libvertex.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwerami,
        "bin\\libwerami.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        MC_fit,
        "bin\\MC_fit.exe",
    )

    JLLWrappers.@init_executable_product(
        actcor,
        "bin\\actcor.exe",
    )

    JLLWrappers.@init_executable_product(
        build,
        "bin\\build.exe",
    )

    JLLWrappers.@init_executable_product(
        convex,
        "bin\\convex.exe",
    )

    JLLWrappers.@init_executable_product(
        ctransf,
        "bin\\ctransf.exe",
    )

    JLLWrappers.@init_executable_product(
        fluids,
        "bin\\fluids.exe",
    )

    JLLWrappers.@init_executable_product(
        frendly,
        "bin\\frendly.exe",
    )

    JLLWrappers.@init_executable_product(
        meemum,
        "bin\\meemum.exe",
    )

    JLLWrappers.@init_executable_product(
        pspts,
        "bin\\pspts.exe",
    )

    JLLWrappers.@init_executable_product(
        pssect,
        "bin\\pssect.exe",
    )

    JLLWrappers.@init_executable_product(
        pstable,
        "bin\\pstable.exe",
    )

    JLLWrappers.@init_executable_product(
        psvdraw,
        "bin\\psvdraw.exe",
    )

    JLLWrappers.@init_executable_product(
        pt2curv,
        "bin\\pt2curv.exe",
    )

    JLLWrappers.@init_executable_product(
        vertex,
        "bin\\vertex.exe",
    )

    JLLWrappers.@init_executable_product(
        werami,
        "bin\\werami.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
