# Autogenerated wrapper script for Perple_X_jll for x86_64-unknown-freebsd-libgfortran4
export MC_fit, actcor, build, convex, ctransf, fluids, frendly, libMC_fit, libactcor, libbuild, libconvex, libctransf, libfluids, libfrendly, libmeemum, libpspts, libpssect, libpstable, libpsvdraw, libpt2curv, libvertex, libwerami, meemum, pspts, pssect, pstable, psvdraw, pt2curv, vertex, werami

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("Perple_X")
JLLWrappers.@declare_library_product(libMC_fit, "libMC_fit.so")
JLLWrappers.@declare_library_product(libactcor, "libactcor.so")
JLLWrappers.@declare_library_product(libbuild, "libbuild.so")
JLLWrappers.@declare_library_product(libconvex, "libconvex.so")
JLLWrappers.@declare_library_product(libctransf, "libctransf.so")
JLLWrappers.@declare_library_product(libfluids, "libfluids.so")
JLLWrappers.@declare_library_product(libfrendly, "libfrendly.so")
JLLWrappers.@declare_library_product(libmeemum, "libmeemum.so")
JLLWrappers.@declare_library_product(libpspts, "libpspts.so")
JLLWrappers.@declare_library_product(libpssect, "libpssect.so")
JLLWrappers.@declare_library_product(libpstable, "libpstable.so")
JLLWrappers.@declare_library_product(libpsvdraw, "libpsvdraw.so")
JLLWrappers.@declare_library_product(libpt2curv, "libpt2curv.so")
JLLWrappers.@declare_library_product(libvertex, "libvertex.so")
JLLWrappers.@declare_library_product(libwerami, "libwerami.so")
JLLWrappers.@declare_executable_product(MC_fit)
JLLWrappers.@declare_executable_product(actcor)
JLLWrappers.@declare_executable_product(build)
JLLWrappers.@declare_executable_product(convex)
JLLWrappers.@declare_executable_product(ctransf)
JLLWrappers.@declare_executable_product(fluids)
JLLWrappers.@declare_executable_product(frendly)
JLLWrappers.@declare_executable_product(meemum)
JLLWrappers.@declare_executable_product(pspts)
JLLWrappers.@declare_executable_product(pssect)
JLLWrappers.@declare_executable_product(pstable)
JLLWrappers.@declare_executable_product(psvdraw)
JLLWrappers.@declare_executable_product(pt2curv)
JLLWrappers.@declare_executable_product(vertex)
JLLWrappers.@declare_executable_product(werami)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        libMC_fit,
        "lib/libMC_fit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libactcor,
        "lib/libactcor.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libbuild,
        "lib/libbuild.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libconvex,
        "lib/libconvex.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libctransf,
        "lib/libctransf.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfluids,
        "lib/libfluids.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libfrendly,
        "lib/libfrendly.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libmeemum,
        "lib/libmeemum.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpspts,
        "lib/libpspts.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpssect,
        "lib/libpssect.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpstable,
        "lib/libpstable.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpsvdraw,
        "lib/libpsvdraw.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpt2curv,
        "lib/libpt2curv.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvertex,
        "lib/libvertex.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libwerami,
        "lib/libwerami.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        MC_fit,
        "bin/MC_fit",
    )

    JLLWrappers.@init_executable_product(
        actcor,
        "bin/actcor",
    )

    JLLWrappers.@init_executable_product(
        build,
        "bin/build",
    )

    JLLWrappers.@init_executable_product(
        convex,
        "bin/convex",
    )

    JLLWrappers.@init_executable_product(
        ctransf,
        "bin/ctransf",
    )

    JLLWrappers.@init_executable_product(
        fluids,
        "bin/fluids",
    )

    JLLWrappers.@init_executable_product(
        frendly,
        "bin/frendly",
    )

    JLLWrappers.@init_executable_product(
        meemum,
        "bin/meemum",
    )

    JLLWrappers.@init_executable_product(
        pspts,
        "bin/pspts",
    )

    JLLWrappers.@init_executable_product(
        pssect,
        "bin/pssect",
    )

    JLLWrappers.@init_executable_product(
        pstable,
        "bin/pstable",
    )

    JLLWrappers.@init_executable_product(
        psvdraw,
        "bin/psvdraw",
    )

    JLLWrappers.@init_executable_product(
        pt2curv,
        "bin/pt2curv",
    )

    JLLWrappers.@init_executable_product(
        vertex,
        "bin/vertex",
    )

    JLLWrappers.@init_executable_product(
        werami,
        "bin/werami",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
